<?php
/**
 * @file
 * Code for the AbleOrganizer Sample Donation Pages feature.
 */

include_once 'ableorganizer_sample_donation_pages.features.inc';

/**
 * Implements hook_post_features_rebuild().
 */
function ableorganizer_sample_donation_pages_post_features_rebuild($component) {
  // Configure the default email settings, if they are enabled.
  if (isset($component) && $component == 'uuid_entities' && variable_get('configure_donation_email', 0) === 1) {
    $fields = array();
    $fields['thanks_email'] = 'rules_cmcd_thank_you_message';
    db_update('crm_core_donation_nodes')->fields($fields)->execute();
  }
}

/**
 * Implements hook_post_features_rebuild().
 */
function ableorganizer_sample_donation_pages_post_features_revert($component) {
  ableorganizer_sample_donation_pages_post_features_rebuild($component);
}
