<?php
/**
 * @file
 * Code for the CRM Core Volunteer sample content feature.
 */

include_once 'ableorganizer_sample_volunteer_pages.features.inc';

/**
 * Implements hook_post_features_rebuild().
 */
function ableorganizer_sample_volunteer_pages_post_features_rebuild($component) {
  // Configure the default email settings, if they are enabled.
  if (isset($component) && $component == 'uuid_node' && variable_get('configure_volunteer_email', 0) === 1) {
    $fields = array();
    $fields['wait_email'] = 'rules_cmcv_wl_notify';
    $fields['sign_email'] = 'rules_cmcv_opportunity_signup';
    db_update('crm_core_volunteer_nodes')->fields($fields)->execute();
  }
}

/**
 * Implements hook_post_features_rebuild().
 */
function ableorganizer_sample_volunteer_pages_post_features_revert($component) {
  ableorganizer_sample_volunteer_pages_post_features_rebuild($component);
}
